Домашнее задание №1
jokerety/2018-FS-21-Frontend-RomanMaslov pull request #1
Opened 2018-10-07 15:19 UTC by jokerety

1) Добавил сборку webpack
2) Изменил функцию say таким образом, чтобы она создавала на странице блок с фоном, отличным от фона страницы и выводила в нем текст сообщения
3) Залил сначала в master, поэтому в изменениях только в index.html

2018-10-07 19:41 UTC, martinkomitsky requested changes
Классические замечания:
1. Убрать папки node_modules, dist из репозитория, добавить их в .gitignore.
2. Заменить во всех js файлах двойные кавычки на одинарные.
3. Проверить отступы в коде - использовать либо 4 пробела, либо 1 таб.

2018-10-08 20:21 UTC, martinkomitsky commented
@jokerety, ты учишься на 2 семестре в группе FS-21? Почему название репозитория "2018-FS-11-Frontend-Maslov"?

2018-10-10 11:29 UTC, jokerety commented
@martinkomitsky ,
1) Добавил .gitignore
2)Заменил на одинарные кавычки
3) Исправил отступы
4) Исправил на FS-21

2018-10-10 12:37 UTC, martinkomitsky commented
Как твое имя? В рамках исключения, допиши еще в название репозитория свое имя, перед фамилией. Вас двое(

2018-10-10 13:27 UTC, jokerety commented
@martinkomitsky Роман, дописал)

2018-10-10 13:28 UTC, martinkomitsky approved these changes

2018-10-10 13:29 UTC, merged

2018-10-10 13:29 UTC, martinkomitsky commented
Спасибо, 10)