h/w 2
jokerety/2018-FS-21-Frontend-RomanMaslov pull request #2
Opened 2018-10-14 18:30 UTC by jokerety

@martinkomitsky 
1) Доработал страницу формы отправки сообщений (имя, фамилия + телефон)
2) Установил Eslint + исправил с его помощью стиль

2018-10-15 12:23 UTC, martinkomitsky commented on .idea/inspectionProfiles/Project_Default.xml
> +<component name="InspectionProjectProfileManager">
Откуда опять это взялось?(((

2018-10-15 12:26 UTC, martinkomitsky requested changes
1. Удали, пожауйста, все папки типа .idea, node_modules, dist из репозитория. Если какой-то нет в `.gitignore`, то их туда надо добавить.
2. Не забывай перед сдачей ДЗ убедиться в том, что твоя текущая ветка up-to-date с мастером. То бишь, надо всегда при сдаче ДЗ либо делать новую ветку от актального master, либо подтягивать в свою, в данном случае, можно выполнить `git pull origin master`

2018-10-17 21:09 UTC, jokerety commented
@martinkomitsky 
1)Удалил папку типа .idea из репозитория
2) выполнил git pull origin master

2018-10-18 11:52 UTC, martinkomitsky commented
> 1)Удалил папку типа .idea из репозитория

![image](https://user-images.githubusercontent.com/14847018/47152443-6645e300-d2e5-11e8-980e-313a68650e30.png)

Ничего не удалил!

2018-10-20 14:00 UTC, jokerety commented
@martinkomitsky 
Прошу прощения( не проверил
1) удалил node_moduler, .idea, dist

2018-10-20 18:38 UTC, martinkomitsky commented
![image](https://user-images.githubusercontent.com/14847018/47259318-837add00-d4b0-11e8-8ae5-680ada93a1a0.png)
а где стили?
@jokerety

2018-10-30 22:25 UTC, jokerety commented
@martinkomitsky 
1) добавил стили
2) из 3-го задания сделал : 1) geo 2) file upload

2018-11-04 07:44 UTC, martinkomitsky approved these changes
Затянууулось все

2018-11-04 07:44 UTC, merged

2018-11-04 07:44 UTC, martinkomitsky commented
Скорее приступай к след дз.
10